WhiteCard.create!([
  {body: "Michelle Obama's arms.", user_id: 1}	,
  {body: "German dungeon porn.", user_id: 1}	,
  {body: "White people.", user_id: 1}	,
  {body: "Getting so angry that you pop a boner.", user_id: 1}	,
  {body: "Tasteful sideboob.", user_id: 1}	,
  {body: "Praying the gay away.", user_id: 1}	,
  {body: "Two midgets shitting into a bucket.", user_id: 1}	,
  {body: "MechaHitler.", user_id: 1}	,
  {body: "Being a motherfucking sorcerer.", user_id: 1}	,
  {body: "A disappointing birthday party.", user_id: 1}	,
  {body: "Puppies!", user_id: 1}	,
  {body: "A windmill full of corpses.", user_id: 1}	,
  {body: "Guys who don't call.", user_id: 1}	,
  {body: "Racially-biased SAT questions.", user_id: 1}	,
  {body: "Dying.", user_id: 1}	,
  {body: "Steven Hawking talking dirty.", user_id: 1}	,
  {body: "Being on fire.", user_id: 1}	,
  {body: "A lifetime of sadness.", user_id: 1}	,
  {body: "An erection that lasts longer than four hours.", user_id: 1}	,
  {body: "AIDS", user_id: 1}	,
  {body: "Same-sex ice dancing.", user_id: 1}	,
  {body: "Glenn Beck catching his scrotum on a curtain hook.", user_id: 1}	,
  {body: "The Rapture.", user_id: 1}	,
  {body: "Pterodactyl eggs.", user_id: 1}	,
  {body: "Crippling debt.", user_id: 1}	,
  {body: "Eugenics.", user_id: 1}	,
  {body: "Exchanging pleasantries.", user_id: 1}	,
  {body: "Dying of dysentery.", user_id: 1}	,
  {body: "Roofies.", user_id: 1}	,
  {body: "Getting naked and watching Nickelodeon.", user_id: 1}	,
  {body: "The forbidden fruit.", user_id: 1}	,
  {body: "Republicans.", user_id: 1}	,
  {body: "The Big Bang.", user_id: 1}	,
  {body: "Anal beads.", user_id: 1}	,
  {body: "Amputees.", user_id: 1}	,
  {body: "Men.", user_id: 1}	,
  {body: "Surprise sex!", user_id: 1}	,
  {body: "Kim Jong-il.", user_id: 1}	,
  {body: "Concealing a boner", user_id: 1}	,
  {body: "Agriculture.", user_id: 1}	,
  {body: "Glenn Beck being harried by a swarm of buzzards.", user_id: 1}	,
  {body: "Making a pouty face.", user_id: 1}	,
  {body: "A salty surprise.", user_id: 1}	,
  {body: "The Jews.", user_id: 1}	,
  {body: "Charisma.", user_id: 1}	,
  {body: "YOU MUST CONSTRUCT ADDITIONAL PYLONS.", user_id: 1}	,
  {body: "Panda sex.", user_id: 1}	,
  {body: "Taking off your shirt.", user_id: 1}	,
  {body: "A drive-by shooting.", user_id: 1}	,
  {body: "Ronald Reagan.", user_id: 1}	,
  {body: "Morgan Freeman's voice.", user_id: 1}	,
  {body: "Breaking out into song and dance.", user_id: 1}	,
  {body: "Jewish fraternities.", user_id: 1}	,
  {body: "Dead babies.", user_id: 1}	,
  {body: "Masturbation.", user_id: 1}	,
  {body: "Hormone injections.", user_id: 1}	,
  {body: "All-you-can-eat shrimp for $4.99.", user_id: 1}	,
  {body: "Incest.", user_id: 1}	,
  {body: "Scalping.", user_id: 1}	,
  {body: "Soup that is too hot.", user_id: 1}	,
  {body: "The &Uuml;bermensch.", user_id: 1}	,
  {body: "Nazis.", user_id: 1}	,
  {body: "Tom Cruise.", user_id: 1}	,
  {body: "Stifling a giggle at the mention of Hutus and Tutsis.", user_id: 1}	,
  {body: "Edible underpants.", user_id: 1}	,
  {body: "The Hustle.", user_id: 1}	,
  {body: "A Super Soaker&trade; full of cat pee.", user_id: 1}	,
  {body: "Figgy pudding.", user_id: 1}	,
  {body: "Object permanence.", user_id: 1}	,
  {body: "Consultants.", user_id: 1}	,
  {body: "Intelligent design.", user_id: 1}	,
  {body: "Nocturnal emissions.", user_id: 1}	,
  {body: "Uppercuts.", user_id: 1}	,
  {body: "Being marginalized.", user_id: 1}	,
  {body: "The profoundly handicapped.", user_id: 1}	,
  {body: "Obesity.", user_id: 1}	,
  {body: "Chutzpah.", user_id: 1}	,
  {body: "Unfathomable stupidity.", user_id: 1}	,
  {body: "Repression.", user_id: 1}	,
  {body: "Attitude.", user_id: 1}	,
  {body: "Passable transvestites.", user_id: 1}	,
  {body: "Party poopers.", user_id: 1}	,
  {body: "The American Dream", user_id: 1}	,
  {body: "Child beauty pageants.", user_id: 1}	,
  {body: "Puberty.", user_id: 1}	,
  {body: "Testicular torsion.", user_id: 1}	,
  {body: "The folly of man.", user_id: 1}	,
  {body: "Nickelback.", user_id: 1}	,
  {body: "Swooping.", user_id: 1}	,
  {body: "Goats eating cans.", user_id: 1}	,
  {body: "The KKK.", user_id: 1}	,
  {body: "Kamikaze pilots.", user_id: 1}	,
  {body: "Horrifying laser hair removal accidents.", user_id: 1}	,
  {body: "Adderall&trade;.", user_id: 1}	,
  {body: "A look-see.", user_id: 1}	,
  {body: "Doing the right thing.", user_id: 1}	,
  {body: "The taint; the grundle; the fleshy fun-bridge.", user_id: 1}	,
  {body: "Lactation.", user_id: 1}	,
  {body: "Pabst Blue Ribbon.", user_id: 1}	,
  {body: "Powerful thighs.", user_id: 1}	,
  {body: "Saxophone solos.", user_id: 1}	,
  {body: "The gays.", user_id: 1}	,
  {body: "A middle-aged man on roller skates.", user_id: 1}	,
  {body: "A foul mouth.", user_id: 1}	,
  {body: "The thing that electrocutes your abs.", user_id: 1}	,
  {body: "Heteronormativity.", user_id: 1}	,
  {body: "Cuddling.", user_id: 1}	,
  {body: "Coat hanger abortions.", user_id: 1}	,
  {body: "A big hoopla about nothing.", user_id: 1}	,
  {body: "Boogers.", user_id: 1}	,
  {body: "A hot mess.", user_id: 1}	,
  {body: "Raptor attacks.", user_id: 1}	,
  {body: "My collection of high-tech sex toys.", user_id: 1}	,
  {body: "Fear itself.", user_id: 1}	,
  {body: "<i>Bees?</i>", user_id: 1}	,
  {body: "Getting drunk on mouthwash.", user_id: 1}	,
  {body: "Sniffing glue.", user_id: 1}	,
  {body: "Oversized lollipops.", user_id: 1}	,
  {body: "An icepick lobotomy.", user_id: 1}	,
  {body: "Being rich.", user_id: 1}	,
  {body: "Friends with benefits.", user_id: 1}	,
  {body: "Teaching a robot to love.", user_id: 1}	,
  {body: "Women's suffrage.", user_id: 1}	,
  {body: "Me time.", user_id: 1}	,
  {body: "The heart of a child.", user_id: 1}	,
  {body: "Smallpox blankets.", user_id: 1}	,
  {body: "The clitoris.", user_id: 1}	,
  {body: "John Wilkes Booth.", user_id: 1}	,
  {body: "The glass ceiling.", user_id: 1}	,
  {body: "Sarah Palin.", user_id: 1}	,
  {body: "Sexy pillow fights.", user_id: 1}	,
  {body: "Yeast.", user_id: 1}	,
  {body: "Full frontal nudity.", user_id: 1}	,
  {body: "Parting the Red Sea.", user_id: 1}	,
  {body: "A Bop It&trade;.", user_id: 1}	,
  {body: "Michael Jackson.", user_id: 1}	,
  {body: "Team-building exercises.", user_id: 1}	,
  {body: "Harry Potter erotica.", user_id: 1}	,
  {body: "Authentic Mexican cuisine.", user_id: 1}	,
  {body: "Frolicking.", user_id: 1}	,
  {body: "Sexting.", user_id: 1}	,
  {body: "Grandma.", user_id: 1}	,
  {body: "Not giving a shit about the Third World.", user_id: 1}	,
  {body: "Licking things to claim them as your own.", user_id: 1}	,
  {body: "Genghis Khan.", user_id: 1}	,
  {body: "The hardworking Mexican.", user_id: 1}	,
  {body: "RoboCop.", user_id: 1}	,
  {body: "My relationship status.", user_id: 1}	,
  {body: "Scrubbing under the folds.", user_id: 1}	,
  {body: "Porn Stars.", user_id: 1}	,
  {body: "Horse meat.", user_id: 1}	,
  {body: "Sunshine and rainbows.", user_id: 1}	,
  {body: "Expecting a burp and vomiting on the floor.", user_id: 1}	,
  {body: "Barack Obama.", user_id: 1}	,
  {body: "Spontaneous human combustion.", user_id: 1}	,
  {body: "Natural selection.", user_id: 1}	,
  {body: "Mouth herpes.", user_id: 1}	,
  {body: "Flash flooding.", user_id: 1}	,
  {body: "Goblins.", user_id: 1}	,
  {body: "A monkey smoking a cigar.", user_id: 1}	,
  {body: "Spectacular abs.", user_id: 1}	,
  {body: "A good sniff.", user_id: 1}	,
  {body: "Wiping her butt.", user_id: 1}	,
  {body: "The Three-Fifths compromise.", user_id: 1}	,
  {body: "Pedophiles.", user_id: 1}	,
  {body: "Doin' it in the butt.", user_id: 1}	,
  {body: "Being fabulous.", user_id: 1}	,
  {body: "Mathletes.", user_id: 1}	,
  {body: "Wearing underwear inside-out to avoid doing laundry.", user_id: 1}	,
  {body: "Nipple blades.", user_id: 1}	,
  {body: "An M. Night Shyamalan plot twist.", user_id: 1}	,
  {body: "A bag of magic beans.", user_id: 1}	,
  {body: "Vigorous jazz hands.", user_id: 1}	,
  {body: "A defective condom.", user_id: 1}	,
  {body: "Skeletor.", user_id: 1}	,
  {body: "Vikings.", user_id: 1}	,
  {body: "Leaving an awkward voicemail.", user_id: 1}	,
  {body: "Teenage pregnancy.", user_id: 1}	,
  {body: "Dead parents.", user_id: 1}	,
  {body: "Hot cheese.", user_id: 1}	,
  {body: "My sex life.", user_id: 1}	,
  {body: "A mopey zoo lion.", user_id: 1}	,
  {body: "Assless chaps.", user_id: 1}	,
  {body: "Riding off into the sunset.", user_id: 1}	,
  {body: "Lance Armstrong's missing testicle.", user_id: 1}	,
  {body: "Sweet, sweet vengeance.", user_id: 1}	,
  {body: "Genital piercings.", user_id: 1}	,
  {body: "Keg stands.", user_id: 1}	,
  {body: "Darth Vader.", user_id: 1}	,
  {body: "Viagra&copy;.", user_id: 1}	,
  {body: "Necrophilia.", user_id: 1}	,
  {body: "A really cool hat.", user_id: 1}	,
  {body: "Toni Morrison's vagina.", user_id: 1}	,
  {body: "An Oedipus complex.", user_id: 1}	,
  {body: "The Tempur-Pedic&copy; Swedish Sleep System&trade;.", user_id: 1}	,
  {body: "Preteens.", user_id: 1}	,
  {body: "Dick fingers.", user_id: 1}	,
  {body: "A cooler full of organs.", user_id: 1}	,
  {body: "Shapeshifters.", user_id: 1}	,
  {body: "The Care Bear Stare.", user_id: 1}	,
  {body: "Erectile dysfunction.", user_id: 1}	,
  {body: "Keanu Reeves.", user_id: 1}	,
  {body: "The Virginia Tech Massacre.", user_id: 1}	,
  {body: "The Underground Railroad.", user_id: 1}	,
  {body: "The chronic.", user_id: 1}	,
  {body: "Queefing.", user_id: 1}	,
  {body: "Heartwarming orphans.", user_id: 1}	,
  {body: "A thermonuclear detonation.", user_id: 1}	,
  {body: "Cheating in the Special Olympics.", user_id: 1}	,
  {body: "Tangled Slinkys.", user_id: 1}	,
  {body: "A moment of silence.", user_id: 1}	,
  {body: "Civilian casualties.", user_id: 1}	,
  {body: "Catapults.", user_id: 1}	,
  {body: "Sharing needles.", user_id: 1}	,
  {body: "Ethnic cleansing.", user_id: 1}	,
  {body: "Emotions.", user_id: 1}	,
  {body: "Children on leashes.", user_id: 1}	,
  {body: "Balls.", user_id: 1}	,
  {body: "Homeless people.", user_id: 1}	,
  {body: "Eating all of the cookies before the AIDS bake-sale.", user_id: 1}	,
  {body: "Old-people smell.", user_id: 1}	,
  {body: "Farting and walking away.", user_id: 1}	,
  {body: "The inevitable heat death of the universe.", user_id: 1}	,
  {body: "The violation of our most basic human rights.", user_id: 1}	,
  {body: "Fingering.", user_id: 1}	,
  {body: "The placenta.", user_id: 1}	,
  {body: "The Rev. Dr. Martin Luther King, Jr.", user_id: 1}	,
  {body: "Leprosy.", user_id: 1}	,
  {body: "Sperm whales.", user_id: 1}	,
  {body: "Multiple stab wounds.", user_id: 1}	,
  {body: "Flightless birds.", user_id: 1}	,
  {body: "Grave robbing.", user_id: 1}	,
  {body: "Home video of Oprah sobbing into a Lean Cuisine&copy;.", user_id: 1}	,
  {body: "Oompa-Loompas.", user_id: 1}	,
  {body: "A murder most foul.", user_id: 1}	,
  {body: "Tentacle porn.", user_id: 1}	,
  {body: "Daddy issues.", user_id: 1}	,
  {body: "Bill Nye the Science Guy.", user_id: 1}	,
  {body: "Peeing a little bit.", user_id: 1}	,
  {body: "The miracle of childbirth.", user_id: 1}	,
  {body: "Tweeting.", user_id: 1}	,
  {body: "Another goddamn vampire movie.", user_id: 1}	,
  {body: "Britney Spears at 55.", user_id: 1}	,
  {body: "New Age music.", user_id: 1}	,
  {body: "The Make-A-Wish&reg; Foundation.", user_id: 1}	,
  {body: "Firing a rifle into the air while balls deep in a squealing hog.", user_id: 1}	,
  {body: "Active listening.", user_id: 1}	,
  {body: "Nicolas Cage.", user_id: 1}	,
  {body: "72 virgins.", user_id: 1}	,
  {body: "Stranger danger.", user_id: 1}	,
  {body: "Hope.", user_id: 1}	,
  {body: "A gassy antelope.", user_id: 1}	,
  {body: "BATMAN!!!", user_id: 1}	,
  {body: "Chivalry.", user_id: 1}	,
  {body: "Passing a kidney stone.", user_id: 1}	,
  {body: "Black people.", user_id: 1}	,
  {body: "Natalie Portman.", user_id: 1}	,
  {body: "A mime having a stroke.", user_id: 1}	,
  {body: "Classist undertones.", user_id: 1}	,
  {body: "Sean Penn.", user_id: 1}	,
  {body: "A mating display.", user_id: 1}	,
  {body: "The Holy Bible.", user_id: 1}	,
  {body: "Hot Pockets&copy;.", user_id: 1}	,
  {body: "A sad handjob.", user_id: 1}	,
  {body: "Pulling out.", user_id: 1}	,
  {body: "Serfdom.", user_id: 1}	,
  {body: "Pixelated bukkake.", user_id: 1}	,
  {body: "Dropping a chandelier on your enemies and riding the rope up.", user_id: 1}	,
  {body: "Jew-fros.", user_id: 1}	,
  {body: "Waiting 'til marriage.", user_id: 1}	,
  {body: "Euphoria&trade; by Calvin Klein.", user_id: 1}	,
  {body: "The World of Warcraft.", user_id: 1}	,
  {body: "Lunchables&trade;.", user_id: 1}	,
  {body: "The Kool-Aid Man.", user_id: 1}	,
  {body: "Drinking ten 5-hour ENERGY; to get fifty continuous hours of energy.", user_id: 1}	,
  {body: "Self-loathing.", user_id: 1}	,
  {body: "A falcon with a cap on its head.", user_id: 1}	,
  {body: "Historically black colleges.", user_id: 1}	,
  {body: "Not reciprocating oral sex.", user_id: 1}	,
  {body: "Global warming.", user_id: 1}	,
  {body: "Ghosts.", user_id: 1}	,
  {body: "World peace.", user_id: 1}	,
  {body: "A can of whoop-ass.", user_id: 1}	,
  {body: "The Dance of the Sugar Plum Fairy.", user_id: 1}	,
  {body: "A zesty breakfast burrito.", user_id: 1}	,
  {body: "Switching to Geico&reg;.", user_id: 1}	,
  {body: "Aaron Burr.", user_id: 1}	,
  {body: "Picking up girls at the abortion clinic.", user_id: 1}	,
  {body: "Land mines.", user_id: 1}	,
  {body: "Former President George W. Bush.", user_id: 1}	,
  {body: "Geese.", user_id: 1}	,
  {body: "Mutually-assured destruction.", user_id: 1}	,
  {body: "College.", user_id: 1}	,
  {body: "Date rape.", user_id: 1}	,
  {body: "Bling.", user_id: 1}	,
  {body: "A gentle caress of the inner thigh.", user_id: 1}	,
  {body: "A time travel paradox.", user_id: 1}	,
  {body: "Seppuku.", user_id: 1}	,
  {body: "Poor life choices.", user_id: 1}	,
  {body: "Waking up half-naked in a Denny's parking lot.", user_id: 1}	,
  {body: "Italians.", user_id: 1}	,
  {body: "GoGurt&reg;.", user_id: 1}	,
  {body: "Finger painting.", user_id: 1}	,
  {body: "Robert Downey, Jr.", user_id: 1}	,
  {body: "My soul.", user_id: 1}	,
  {body: "Smegma.", user_id: 1}	,
  {body: "Embryonic stem cells.", user_id: 1}	,
  {body: "The South.", user_id: 1}	,
  {body: "Christopher Walken.", user_id: 1}	,
  {body: "Gloryholes.", user_id: 1}	,
  {body: "Pretending to care.", user_id: 1}	,
  {body: "Public ridicule.", user_id: 1}	,
  {body: "A tiny horse.", user_id: 1}	,
  {body: "Arnold Schwarzenegger.", user_id: 1}	,
  {body: "A stray pube.", user_id: 1}	,
  {body: "Jerking off into a pool of children's tears.", user_id: 1}	,
  {body: "Child abuse.", user_id: 1}	,
  {body: "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.", user_id: 1}	,
  {body: "Menstruation.", user_id: 1}	,
  {body: "A sassy black woman.", user_id: 1}	,
  {body: "Re-gifting.", user_id: 1}	,
  {body: "Penis envy.", user_id: 1}	,
  {body: "A sausage festival.", user_id: 1}	,
  {body: "Getting really high.", user_id: 1}	,
  {body: "Drinking alone.", user_id: 1}	,
  {body: "Too much hair gel.", user_id: 1}	,
  {body: "Hulk Hogan.", user_id: 1}	,
  {body: "Overcompensation.", user_id: 1}	,
  {body: "Foreskin.", user_id: 1}	,
  {body: "Free samples.", user_id: 1}	,
  {body: "Shaquille O'Neal's acting career.", user_id: 1}	,
  {body: "Five-Dollar Footlongs&trade;.", user_id: 1}	,
  {body: "Whipping it out.", user_id: 1}	,
  {body: "A snapping turtle biting the tip of your penis.", user_id: 1}	,
  {body: "Muhammad (Praise Be Unto Him).", user_id: 1}	,
  {body: "Half-assed foreplay.", user_id: 1}	,
  {body: "Dental dams.", user_id: 1}	,
  {body: "Being a dick to children.", user_id: 1}	,
  {body: "Famine.", user_id: 1}	,
  {body: "Chainsaws for hands.", user_id: 1}	,
  {body: "A gypsy curse.", user_id: 1}	,
  {body: "AXE Body Spray.", user_id: 1}	,
  {body: "The Force.", user_id: 1}	,
  {body: "Explosions.", user_id: 1}	,
  {body: "Cybernetic enhancements.", user_id: 1}	,
  {body: "Customer service representatives.", user_id: 1}	,
  {body: "White privilege.", user_id: 1}	,
  {body: "Gandhi.", user_id: 1}	,
  {body: "Road head.", user_id: 1}	,
  {body: "God.", user_id: 1}	,
  {body: "Poorly-timed Holocaust jokes.", user_id: 1}	,
  {body: "8 oz. of sweet Mexican black-tar heroin.", user_id: 1}	,
  {body: "Judge Judy.", user_id: 1}	,
  {body: "The Little Engine That Could.", user_id: 1}	,
  {body: "Altar boys.", user_id: 1}	,
  {body: "Mr. Clean, right behind you.", user_id: 1}	,
  {body: "Vehicular manslaughter.", user_id: 1}	,
  {body: "Dwarf tossing.", user_id: 1}	,
  {body: "Friction.", user_id: 1}	,
  {body: "Lady Gaga.", user_id: 1}	,
  {body: "Scientology.", user_id: 1}	,
  {body: "Justin Bieber.", user_id: 1}	,
  {body: "A death ray.", user_id: 1}	,
  {body: "Vigilante justice.", user_id: 1}	,
  {body: "The Pope.", user_id: 1}	,
  {body: "A sea of troubles.", user_id: 1}	,
  {body: "Alcoholism.", user_id: 1}	,
  {body: "Poor people.", user_id: 1}	,
  {body: "A fetus.", user_id: 1}	,
  {body: "Women in yogurt commercials.", user_id: 1}	,
  {body: "Exactly what you'd expect.", user_id: 1}	,
  {body: "Flesh-eating bacteria.", user_id: 1}	,
  {body: "My genitals.", user_id: 1}	,
  {body: "A balanced breakfast.", user_id: 1}	,
  {body: "Dick Cheney.", user_id: 1}	,
  {body: "Lockjaw.", user_id: 1}	,
  {body: "Natural male enhancement.", user_id: 1}	,
  {body: "Take-backsies.", user_id: 1}	,
  {body: "Winking at old people.", user_id: 1}	,
  {body: "Opposable thumbs.", user_id: 1}	,
  {body: "Flying sex snakes.", user_id: 1}	,
  {body: "Passive-aggressive Post-it notes.", user_id: 1}	,
  {body: "Inappropriate yodeling.", user_id: 1}	,
  {body: "Golden showers.", user_id: 1}	,
  {body: "Racism.", user_id: 1}	,
  {body: "Copping a feel.", user_id: 1}	,
  {body: "Auschwitz.", user_id: 1}	,
  {body: "Elderly Japanese men.", user_id: 1}	,
  {body: "Raping and pillaging.", user_id: 1}	,
  {body: "Kids with ass cancer.", user_id: 1}	,
  {body: "Pictures of boobs.", user_id: 1}	,
  {body: "The homosexual agenda.", user_id: 1}	,
  {body: "A homoerotic volleyball montage.", user_id: 1}	,
  {body: "Sexual tension.", user_id: 1}	,
  {body: "Hurricane Katrina.", user_id: 1}	,
  {body: "Fiery poops.", user_id: 1}	,
  {body: "Science.", user_id: 1}	,
  {body: "Dry heaving.", user_id: 1}	,
  {body: "Cards Against Humanity.", user_id: 1}	,
  {body: "Fancy Feast.", user_id: 1}	,
  {body: "A bleached asshole.", user_id: 1}	,
  {body: "Lumberjack fantasies.", user_id: 1}	,
  {body: "American Gladiators.", user_id: 1}	,
  {body: "Autocannibalism.", user_id: 1}	,
  {body: "Sean Connery.", user_id: 1}	,
  {body: "William Shatner.", user_id: 1}	,
  {body: "Domino's Oreo Dessert Pizza.", user_id: 1}	,
  {body: "An asymmetric boob job.", user_id: 1}	,
  {body: "Centaurs.", user_id: 1}	,
  {body: "A micropenis.", user_id: 1}	,
  {body: "Asians who aren't good at math.", user_id: 1}	,
  {body: "The milk man.", user_id: 1}	,
  {body: "Waterboarding.", user_id: 1}	,
  {body: "Wifely duties.", user_id: 1}	,
  {body: "Loose lips.", user_id: 1}	,
  {body: "The Blood of Christ.", user_id: 1}	,
  {body: "Actually taking candy from a baby.", user_id: 1}	,
  {body: "The token minority.", user_id: 1}	,
  {body: "Jibber-jabber.", user_id: 1}	,
  {body: "A brain tumor.", user_id: 1}	,
  {body: "Bingeing and purging.", user_id: 1}	,
  {body: "A clandestine butt scratch.", user_id: 1}	,
  {body: "The Chinese gymnastics team.", user_id: 1}	,
  {body: "Prancing.", user_id: 1}	,
  {body: "The Hamburglar.", user_id: 1}	,
  {body: "Police brutality.", user_id: 1}	,
  {body: "Man meat.", user_id: 1}	,
  {body: "Forgetting the Alamo.", user_id: 1}	,
  {body: "Eating the last known bison.", user_id: 1}	,
  {body: "Crystal meth.", user_id: 1}	,
  {body: "Booby-trapping the house to foil burglars.", user_id: 1}	,
  {body: "My inner demons.", user_id: 1}	,
  {body: "Third base.", user_id: 1}	,
  {body: "Soiling oneself.", user_id: 1}	,
  {body: "Laying an egg.", user_id: 1}	,
  {body: "Giving 110%.", user_id: 1}	,
  {body: "Hot people.", user_id: 1}	,
  {body: "Friendly fire.", user_id: 1}	,
  {body: "Count Chocula.", user_id: 1}	,
  {body: "Pac-Man uncontrollably guzzling cum.", user_id: 1}	,
  {body: "Estrogen.", user_id: 1}	,
  {body: "My vagina.", user_id: 1}	,
  {body: "Kanye West.", user_id: 1}	,
  {body: "A robust mongoloid.", user_id: 1}	,
  {body: "The Donald Trump Seal of Approval&trade;.", user_id: 1}	,
  {body: "The true meaning of Christmas.", user_id: 1}	,
  {body: "Her Royal Highness, Queen Elizabeth II.", user_id: 1}	,
  {body: "An honest cop with nothing left to lose.", user_id: 1}	,
  {body: "Feeding Rosie O'Donnell.", user_id: 1}	,
  {body: "The Amish.", user_id: 1}	,
  {body: "The terrorists.", user_id: 1}	,
  {body: "When you fart and a little bit comes out.", user_id: 1}	,
  {body: "Pooping back and forth. Forever.", user_id: 1}	,
  {body: "Friends who eat all the snacks.", user_id: 1}	,
  {body: "Cockfights.", user_id: 1}	,
  {body: "Bitches.", user_id: 1}	,
  {body: "Seduction.", user_id: 1}	,
  {body: "A big black dick.", user_id: 1}	,
  {body: "A beached whale.", user_id: 1}	,
  {body: "A bloody pacifier.", user_id: 1}	,
  {body: "A crappy little hand.", user_id: 1}	,
  {body: "A low standard of living.", user_id: 1}	,
  {body: "A nuanced critique.", user_id: 1}	,
  {body: "Panty raids.", user_id: 1}	,
  {body: "A passionate Latino lover.", user_id: 1}	,
  {body: "A rival dojo.", user_id: 1}	,
  {body: "A web of lies.", user_id: 1}	,
  {body: "A woman scorned.", user_id: 1}	,
  {body: "Clams.", user_id: 1}	,
  {body: "Apologizing.", user_id: 1}	,
  {body: "A plunger to the face.", user_id: 1}	,
  {body: "Neil Patrick Harris.", user_id: 1}	,
  {body: "Beating your wives.", user_id: 1}	,
  {body: "Being a dinosaur.", user_id: 1}	,
  {body: "Shaft.", user_id: 1}	,
  {body: "Bosnian chicken farmers.", user_id: 1}	,
  {body: "Nubile slave boys.", user_id: 1}	,
  {body: "Carnies.", user_id: 1}	,
  {body: "Coughing into a vagina.", user_id: 1}	,
  {body: "Suicidal thoughts.", user_id: 1}	,
  {body: "The ooze.", user_id: 1}	,
  {body: "Deflowering the princess.", user_id: 1}	,
  {body: "Dorito breath.", user_id: 1}	,
  {body: "Eating an albino.", user_id: 1}	,
  {body: "Enormous Scandinavian women.", user_id: 1}	,
  {body: "Fabricating statistics.", user_id: 1}	,
  {body: "Finding a skeleton.", user_id: 1}	,
  {body: "Gandalf.", user_id: 1}	,
  {body: "Genetically engineered super-soldiers.", user_id: 1}	,
  {body: "George Clooney's musk.", user_id: 1}	,
  {body: "Getting abducted by Peter Pan.", user_id: 1}	,
  {body: "Getting in her pants, politely.", user_id: 1}	,
  {body: "Gladiatorial combat.", user_id: 1}	,
  {body: "Clenched butt cheeks.", user_id: 1}	,
  {body: "Hipsters.", user_id: 1}	,
  {body: "Historical revisionism.", user_id: 1}	,
  {body: "Insatiable bloodlust.", user_id: 1}	,
  {body: "Jafar.", user_id: 1}	,
  {body: "Jean-Claude Van Damme.", user_id: 1}	,
  {body: "Just the tip.", user_id: 1}	,
  {body: "Mad hacky-sack skills.", user_id: 1}	,
  {body: "Leveling up.", user_id: 1}	,
  {body: "Literally eating shit.", user_id: 1}	,
  {body: "Making the penises kiss.", user_id: 1}	,
  {body: "24-hour media coverage.", user_id: 1}	,
  {body: "Medieval Times&copy; Dinner & Tournament.", user_id: 1}	,
  {body: "Moral ambiguity.", user_id: 1}	,
  {body: "My machete.", user_id: 1}	,
  {body: "One thousand Slim Jims.", user_id: 1}	,
  {body: "Ominous background music.", user_id: 1}	,
  {body: "Overpowering your father.", user_id: 1}	,
  {body: "Stockholm Syndrome.", user_id: 1}	,
  {body: "Quiche.", user_id: 1}	,
  {body: "Quivering jowls.", user_id: 1}	,
  {body: "Revenge fucking.", user_id: 1}	,
  {body: "Ripping into a man's chest and pulling out his still-beating heart.", user_id: 1}	,
  {body: "Ryan Gosling riding in on a white horse.", user_id: 1}	,
  {body: "Santa Claus.", user_id: 1}	,
  {body: "Scrotum tickling.", user_id: 1}	,
  {body: "Sexual humiliation.", user_id: 1}	,
  {body: "Sexy Siamese twins.", user_id: 1}	,
  {body: "Saliva.", user_id: 1}	,
  {body: "Space muffins.", user_id: 1}	,
  {body: "Statistically validated stereotypes.", user_id: 1}	,
  {body: "Sudden Poop Explosion Disease.", user_id: 1}	,
  {body: "The boners of the elderly.", user_id: 1}	,
  {body: "The economy.", user_id: 1}	,
  {body: "Syphilitic insanity.", user_id: 1}	,
  {body: "The Gulags.", user_id: 1}	,
  {body: "The harsh light of day.", user_id: 1}	,
  {body: "The hiccups.", user_id: 1}	,
  {body: "The shambling corpse of Larry King.", user_id: 1}	,
  {body: "The four arms of Vishnu.", user_id: 1}	,
  {body: "Being a busy adult with many important things to do.", user_id: 1}	,
  {body: "Tripping balls.", user_id: 1}	,
  {body: "Words, words, words.", user_id: 1}	,
  {body: "Zeus's sexual appetites.", user_id: 1}	,
  {body: "A bigger, blacker dick.", user_id: 1}	,
  {body: "The mere concept of Applebee's&reg;.", user_id: 1}	,
  {body: "A sad fat dragon with no friends.", user_id: 1}	,
  {body: "Catastrophic urethral trauma.", user_id: 1}	,
  {body: "Hillary Clinton's death stare.", user_id: 1}	,
  {body: "Existing.", user_id: 1}	,
  {body: "A pinata full of scorpions.", user_id: 1}	,
  {body: "Mooing.", user_id: 1}	,
  {body: "Swiftly achieving orgasm.", user_id: 1}	,
  {body: "Daddy's belt.", user_id: 1}	,
  {body: "Double penetration.", user_id: 1}	,
  {body: "Weapons-grade plutonium.", user_id: 1}	,
  {body: "Some really fucked-up shit.", user_id: 1}	,
  {body: "Subduing a grizzly bear and making her your wife.", user_id: 1}	,
  {body: "Rising from the grave.", user_id: 1}	,
  {body: "The mixing of the races.", user_id: 1}	,
  {body: "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.", user_id: 1}	,
  {body: "Scrotal frostbite.", user_id: 1}	,
  {body: "All of this blood.", user_id: 1}	,
  {body: "Loki, the trickster god.", user_id: 1}	,
  {body: "Whining like a little bitch.", user_id: 1}	,
  {body: "Pumping out a baby every nine months.", user_id: 1}	,
  {body: "Tongue.", user_id: 1}	,
  {body: "Finding Waldo.", user_id: 1}	,
  {body: "Upgrading homeless people to mobile hotspots.", user_id: 1}	,
  {body: "Wearing an octopus for a hat.", user_id: 1}	,
  {body: "An unhinged ferris wheel rolling toward the sea.", user_id: 1}	,
  {body: "Living in a trashcan.", user_id: 1}	,
  {body: "The corporations.", user_id: 1}	,
  {body: "A magic hippie love cloud.", user_id: 1}	,
  {body: "Fuck Mountain.", user_id: 1}	,
  {body: "Survivor's guilt.", user_id: 1}	,
  {body: "Me.", user_id: 1}	,
  {body: "Getting hilariously gang-banged by the Blue Man Group.", user_id: 1}	,
  {body: "Jeff Goldblum.", user_id: 1}	,
  {body: "Making a friend.", user_id: 1}	,
  {body: "A soulful rendition of &#34;Ol' Man River.&#34;", user_id: 1}	,
  {body: "Intimacy problems.", user_id: 1}	,
  {body: "A sweaty, panting leather daddy.", user_id: 1}	,
  {body: "Spring break!", user_id: 1}	,
  {body: "Being awesome at sex.", user_id: 1}	,
  {body: "Dining with cardboard cutouts of the cast of &#34;Friends.&#34;", user_id: 1}	,
  {body: "Another shot of morphine.", user_id: 1}	,
  {body: "Beefin' over turf.", user_id: 1}	,
  {body: "A squadron of moles wearing aviator goggles.", user_id: 1}	,
  {body: "Bullshit.", user_id: 1}	,
  {body: "The Google.", user_id: 1}	,
  {body: "Pretty Pretty Princess Dress-Up Board Game&#174;.", user_id: 1}	,
  {body: "The new Radiohead album.", user_id: 1}	,
  {body: "An army of skeletons.", user_id: 1}	,
  {body: "A man in yoga pants with a ponytail and feather earrings.", user_id: 1}	,
  {body: "Mild autism.", user_id: 1}	,
  {body: "Nunchuck moves.", user_id: 1}	,
  {body: "Whipping a disobedient slave.", user_id: 1}	,
  {body: "An ether-soaked rag.", user_id: 1}	,
  {body: "A sweet spaceship.", user_id: 1}	,
  {body: "A 55-gallon drum of lube.", user_id: 1}	,
  {body: "Special musical guest, Cher.", user_id: 1}	,
  {body: "The human body.", user_id: 1}	,
  {body: "Boris the Soviet Love Hammer.", user_id: 1}	,
  {body: "The grey nutrient broth that sustains Mitt Romney.", user_id: 1}	,
  {body: "Tiny nipples.", user_id: 1}	,
  {body: "Power.", user_id: 1}	,
  {body: "Oncoming traffic.", user_id: 1}	,
  {body: "A dollop of sour cream.", user_id: 1}	,
  {body: "A slightly shittier parallel universe.", user_id: 1}	,
  {body: "My first kill.", user_id: 1}	,
  {body: "Graphic violence, adult language, and some sexual content.", user_id: 1}	,
  {body: "Fetal alcohol syndrome.", user_id: 1}	,
  {body: "The day the birds attacked.", user_id: 1}	,
  {body: "One Ring to rule them all.", user_id: 1}	,
  {body: "Grandpa's ashes.", user_id: 1}	,
  {body: "Basic human decency.", user_id: 1}	,
  {body: "A Burmese tiger pit.", user_id: 1}	,
  {body: "Death by Steven Seagal", user_id: 1}	,
  {body: "Dragon boobs.", user_id: 1}	,
  {body: "Verisimilitude.", user_id: 1}	,
  {body: "Dissociated mechanics.", user_id: 1}	,
  {body: "Rape.", user_id: 1}	,
  {body: "Storygames.", user_id: 1}	,
  {body: "Random chargen", user_id: 1}	,
  {body: "RPG.net.", user_id: 1}	,
  {body: "Dice inserted somewhere painful.", user_id: 1}	,
  {body: "FATAL.", user_id: 1}	,
  {body: "Ron Edwards' brain damage.", user_id: 1}	,
  {body: "Boob plate armor.", user_id: 1}	,
  {body: "Gamer chicks.", user_id: 1}	,
  {body: "GNS theory.", user_id: 1}	,
  {body: "Drizzt.", user_id: 1}	,
  {body: "The entire Palladium Books&reg; Megaverse&trade;", user_id: 1}	,
  {body: "BadWrongFun.", user_id: 1}	,
  {body: "Misogynerds.", user_id: 1}	,
  {body: "Cultural Marxism.", user_id: 1}	,
  {body: "Pissing on Gary Gygax's grave.", user_id: 1}	,
  {body: "Steve Jackson's beard.", user_id: 1}	,
  {body: "Natural 20.", user_id: 1}	,
  {body: "Rapenards.", user_id: 1}	,
  {body: "The Crisis of Treachery&trade;.", user_id: 1}	,
  {body: "Game balance.", user_id: 1}	,
  {body: "Fishmalks.", user_id: 1}	,
  {body: "A kick to the dicebags.", user_id: 1}	,
  {body: "Bearded dwarven women.", user_id: 1}	,
  {body: "Owlbear's tears.", user_id: 1}	,
  {body: "Magic missile.", user_id: 1}	,
  {body: "THAC0.", user_id: 1}	,
  {body: "Bigby's Groping Hands.", user_id: 1}	,
  {body: "Drow blackface.", user_id: 1}	,
  {body: "Save or die.", user_id: 1}	,
  {body: "Swine.", user_id: 1}	,
  {body: "The Forge.", user_id: 1}	,
  {body: "Healing Surges.", user_id: 1}	,
  {body: "Gelatinous Cubes.", user_id: 1}	,
  {body: "Total Party Kill.", user_id: 1}	,
  {body: "Quoting Monty Python.", user_id: 1}	,
  {body: "Dumbed down shit for ADD WoW babies.", user_id: 1}	,
  {body: "Mike Mearls.", user_id: 1}	,
  {body: "Comeliness.", user_id: 1}	,
  {body: "Vampire: The Masquerade.", user_id: 1}	,
  {body: "Rifts&trade;.", user_id: 1}	,
  {body: "The random prostitute table.", user_id: 1}	,
  {body: "Dildo of Enlightenment +2", user_id: 1}	,
  {body: "Grognards Against Humanity.", user_id: 1}	,
  {body: "Cthulhu.", user_id: 1}	,
  {body: "The naked succubus in the Monster Manual.", user_id: 1}	,
  {body: "Role-playing and roll-playing.", user_id: 1}	,
  {body: "Fun Tyrant.", user_id: 1}	,
  {body: "4rries.", user_id: 1}	,
  {body: "Martial dailies.", user_id: 1}	,
  {body: "Black Tokyo.", user_id: 1}	,
  {body: "Killfuck Soulshitter.", user_id: 1}	,
  {body: "Cheetoism.", user_id: 1}	,
  {body: "Grimdark.", user_id: 1}	,
  {body: "Kobolds.", user_id: 1}	,
  {body: "Oozemaster.", user_id: 1}	,
  {body: "Rocks fall, everyone dies.", user_id: 1}	,
  {body: "Mark Rein&middot;Hagen.", user_id: 1}	,
  {body: "Maid RPG.", user_id: 1}	,
  {body: "Splugorth blind warrior women.", user_id: 1}	,
  {body: "Dying during chargen.", user_id: 1}	,
  {body: "Slaughtering innocent orc children.", user_id: 1}	,
  {body: "Lesbian stripper ninjas.", user_id: 1}	,
  {body: "Magical tea party.", user_id: 1}	,
  {body: "Grinding levels.", user_id: 1}	,
  {body: "Dice animism.", user_id: 1}	,
  {body: "White privilege.", user_id: 1}	,
  {body: "Githyanki therapy.", user_id: 1}	,
  {body: "Amber Diceless Roleplaying.", user_id: 1}	,
  {body: "A ratcatcher with a small but vicious dog.", user_id: 1}	,
  {body: "Bribing the GM with sexual favors.", user_id: 1}	,
  {body: "Eurocentric fantasy.", user_id: 1}	,
  {body: "Sacred cows.", user_id: 1}	,
  {body: "Gygaxian naturalism.", user_id: 1}	,
  {body: "Special snowflakes.", user_id: 1}	,
  {body: "Neckbeards.", user_id: 1}	,
  {body: "Gazebos.", user_id: 1}	,
  {body: "Lorraine Williams.", user_id: 1}	,
  {body: "Nude larping.", user_id: 1}	,
  {body: "Portable holes.", user_id: 1}	,
  {body: "Steampunk bullshit.", user_id: 1}	,
  {body: "Dump stats.", user_id: 1}	,
  {body: "Ale and whores.", user_id: 1}	,
  {body: "Japanese schoolgirl porn.", user_id: 1}	,
  {body: "Horny catgirls.", user_id: 1}	,
  {body: "Japanese people.", user_id: 1}	,
  {body: "Cimo.", user_id: 1}	,
  {body: "ZA WARUDO!", user_id: 1}	,
  {body: "40 gigs of lolicon.", user_id: 1}	,
  {body: "Goku's hair.", user_id: 1}	,
  {body: "Slashfic.", user_id: 1}	,
  {body: "Star Gentle Uterus", user_id: 1}	,
  {body: "Naruto headbands.", user_id: 1}	,
  {body: "Homestuck troll horns.", user_id: 1}	,
  {body: "Hayao Miyazaki.", user_id: 1}	,
  {body: "The tsunami.", user_id: 1}	,
  {body: "Death Note.", user_id: 1}	,
  {body: "Small breasts.", user_id: 1}	,
  {body: "Asians being racist against each other.", user_id: 1}	,
  {body: "Weeaboo bullshit.", user_id: 1}	,
  {body: "Tsundere.", user_id: 1}	,
  {body: "Body pillows.", user_id: 1}	,
  {body: "A lifelike silicone love doll.", user_id: 1}	,
  {body: "Anime figures drenched in jizz.", user_id: 1}	,
  {body: "Surprise sex.", user_id: 1}	,
  {body: "Yaoi.", user_id: 1}	,
  {body: "Girls with glasses.", user_id: 1}	,
  {body: "Bronies.", user_id: 1}	,
  {body: "Blue and white striped panties.", user_id: 1}	,
  {body: "4chan.", user_id: 1}	,
  {body: "Hello Kitty vibrator.", user_id: 1}	,
  {body: "Finishing attack.", user_id: 1}	,
  {body: "Keikaku* *(keikaku means plan).", user_id: 1}	,
  {body: "Hatsune Miku's screams.", user_id: 1}	,
  {body: "School swimsuits.", user_id: 1}	,
  {body: "Lovingly animated bouncing boobs.", user_id: 1}	,
  {body: "Dragon Balls.", user_id: 1}	,
  {body: "Zangief's chest hair.", user_id: 1}	,
  {body: "DeviantArt.", user_id: 1}	,
  {body: "Giant fucking robots.", user_id: 1}	,
  {body: "Crossplay.", user_id: 1}	,
  {body: "Moeblob.", user_id: 1}	,
  {body: "Carl Macek's rotting corpse.", user_id: 1}	,
  {body: "My waifu.", user_id: 1}	,
  {body: "Voice actress Megumi Hayashibara.", user_id: 1}	,
  {body: "Lynn Minmei.", user_id: 1}	,
  {body: "Panty shots.", user_id: 1}	,
  {body: "Love and Justice.", user_id: 1}	,
  {body: "Consensual tentacle rape.", user_id: 1}	,
  {body: "Gundam.", user_id: 1}	,
  {body: "Captain Bright slapping Amuro.", user_id: 1}	,
  {body: "The Wave Undulation Cannon.", user_id: 1}	,
  {body: "Having sex in the P.E. equipment shed.", user_id: 1}	,
  {body: "Tainted sushi.", user_id: 1}	,
  {body: "Shitty eurobeat music.", user_id: 1}	,
  {body: "Bad dubbing.", user_id: 1}	,
  {body: "Fangirls.", user_id: 1}	,
  {body: "Kawaii desu uguu.", user_id: 1}	,
  {body: "Futanari.", user_id: 1}	,
  {body: "Lesbian schoolgirls.", user_id: 1}	,
  {body: "Osamu Tezuka, rolling in his grave forever.", user_id: 1}	,
  {body: "FUNimation.", user_id: 1}	,
  {body: "Underage cosplayers in bondage gear.", user_id: 1}	,
  {body: "Jackie Chan.", user_id: 1}	,
  {body: "Exchanging Pocky for sexual favors.", user_id: 1}	,
  {body: "Shipping.", user_id: 1}	,
  {body: "Chiyo's father.", user_id: 1}	,
  {body: "Magikarp.", user_id: 1}	,
  {body: "Derpy.", user_id: 1}	,
  {body: "Nanoha and her special friend Fate.", user_id: 1}	,
  {body: "The marbles from Ramune bottles.", user_id: 1}	,
  {body: "Wideface.", user_id: 1}	,
  {body: "Spoilers.", user_id: 1}	,
  {body: "Man-Faye.", user_id: 1}	,
  {body: "Oppai mousepads.", user_id: 1}	,
  {body: "Another dimension.", user_id: 1}	,
  {body: "Homura sniffing Madoka's panties.", user_id: 1}	,
  {body: "Hadouken.", user_id: 1}	,
  {body: "Asian ball-jointed dolls.", user_id: 1}	,
  {body: "J-list.", user_id: 1}	,
  {body: "Childhood friends.", user_id: 1}	,
  {body: "Monkey D. Luffy's rubbery cock.", user_id: 1}	,
  {body: "Cloud's giant fucking Buster Swords.", user_id: 1}	,
  {body: "Taking a dump in Char's helmet.", user_id: 1}	,
  {body: "Hentai marathons.", user_id: 1}	,
  {body: "Gothic Lolita.", user_id: 1}	,
  {body: "Onaholes.", user_id: 1}	,
  {body: "Super Saiyan Level 2.", user_id: 1}	,
  {body: "Gaia Online.", user_id: 1}	,
  {body: "Santa's heavy sack.", user_id: 1}	,
  {body: "Clearing a bloody path through Walmart with a scimitar.", user_id: 1}	,
  {body: "Another shitty year.", user_id: 1}	,
  {body: "Whatever Kwanzaa is supposed to be about.", user_id: 1}	,
  {body: "A Christmas stocking full of coleslaw.", user_id: 1}	,
  {body: "Elf cum.", user_id: 1}	,
  {body: "The tiny, calloused hands of the Chinese children that made this card.", user_id: 1}	,
  {body: "Taking down Santa with a surface-to-air missile.", user_id: 1}	,
  {body: "Socks.", user_id: 1}	,
  {body: "Pretending to be happy.", user_id: 1}	,
  {body: "Krampus, the Austrian Christmas monster.", user_id: 1}	,
  {body: "The Star Wars Holiday Special.", user_id: 1}	,
  {body: "My hot cousin.", user_id: 1}	,
  {body: "Mall Santa.", user_id: 1}	,
  {body: "Several intertwining love stories featuring Hugh Grant.", user_id: 1}	,
  {body: "A Hungry-Man&trade; Frozen Christmas Dinner for one.", user_id: 1}	,
  {body: "Gift-wrapping a live hamster.", user_id: 1}	,
  {body: "Space Jam on VHS.", user_id: 1}	,
  {body: "Immaculate conception.", user_id: 1}	,
  {body: "Fucking up 'Silent Night' in front of 300 parents.", user_id: 1}	,
  {body: "A visually arresting turtleneck.", user_id: 1}	,
  {body: "A toxic family environment.", user_id: 1}	,
  {body: "Eating an entire snowman.", user_id: 1}	,
  {body: "Bumpses.", user_id: 1}	,
  {body: "A Vin Gerard H8 X 10.", user_id: 1}	,
  {body: "Harry Acropolis.", user_id: 1}	,
  {body: "Under the ring.", user_id: 1}	,
  {body: "Afa The Wild Samoan.", user_id: 1}	,
  {body: "Peanut Butter and Baby sandwiches.", user_id: 1}	,
  {body: "Yard Tards.", user_id: 1}	,
  {body: "Two girls, one cup.", user_id: 1}	,
  {body: "Ugly Mexican Hookers.", user_id: 1}	,
  {body: "Duct tape.", user_id: 1}	,
  {body: "Sodaj.", user_id: 1}	,
  {body: "Steve The Teacher.", user_id: 1}	,
  {body: "Jefferee.", user_id: 1}	,
  {body: "Autoerotic Asphyxiation.", user_id: 1}	,
  {body: "Sonic The Hedgehog.", user_id: 1}	,
  {body: "Lotto Money.", user_id: 1}	,
  {body: "Jailbait.", user_id: 1}	,
  {body: "Prison rape.", user_id: 1}	,
  {body: "Two And A Half Men.", user_id: 1}
])
